### ISSUE TITLE
进入本子介绍界面的FAB位置异常

### ISSUE THREAD

**Issue by seasonyuu** [fython/NHentai-android#10]
![screenshot_moe feng nhentai_2015-10-05-15-02-43](https://cloud.githubusercontent.com/assets/8638535/10274645/8acfe88e-6b72-11e5-9227-60b8c319a030.png)
fab大概margin没处理好  另外遮挡住标题了

**Comment by seasonyuu** [comment]
补充  设别 小米note标准版 MIUI7 4.4

**Comment by fython** [comment]
是的，只有 SDK 21 以下出现这个问题。
虽然问题很简单我也没时间修了QAQ，欢迎提 Pull Request~

**Comment by seasonyuu** [comment]
OK 很简单的东西

**Comment by fython** [comment]
Fixed e5ce30339282b9e7e17cddafeb504b02037a2e5e
