### ISSUE TITLE
名称许可

### ISSUE THREAD

**Issue by frankwei98** [fython/NHentai-android#18]
烧饼你好,

请问我能不能用 NHBook 这个名字来开发网站或者开发iOS的 App ?

顺提 我可以免费提供CDN来规避墙的限制（现在不挂SS不能打开）

**Comment by fython** [comment]
很抱歉现在才回复。

我不是很清楚名称使用授权这一块，或许你可以不用我的授权直接使用，但我个人是不希望其他人使用，主要是想让这个应用保持低调。
所以我也不打算加入 CDN 或其他中转服务，让墙成为一个使用门槛。（不排除支持自定义第三方 API 来源，允许用户自行添加源）

**Comment by frankwei98** [comment]
行 那我换个名字吧
顺便问一下要不要 NHBook.xyz 这个域名 我刚注册没多久 可以免费转让给你哦

**Comment by fython** [comment]
不用了，谢谢啦
