### ISSUE TITLE
Set a higher minimum SDK version for better supporting

### ISSUE THREAD

**Issue by fython** [fython/NHentai-android#2]
也許會失去很多用戶，不過這樣能放心的使用一些新特性而不用擔憂兼容性問題了（其實就是開發者很懶很懶，為了加快開發進度想了此下策）。

**Comment by cthbleachbit** [comment]
兹磁，我现在手头的三棒S2电信定制机都有Lolipop了，我身边的HTC啥的也都升到5.x了

**Comment by mouyase** [comment]
支持

**Comment by Qixingchen** [comment]
​支持 5.X 大法好​

2015-09-16 14:56 GMT+08:00 某亚瑟 <notifications@github.com>:

**Comment by drakeet** [comment]
兹磁~~~

**Comment by TonyZzx** [comment]
肉肉肉！至少4.4好不好伐！（祖传4.4的米4很怨念

**Comment by sflower1996** [comment]
当然支持啊

**Comment by dyguests** [comment]
作者好厉害,点个赞!
虽然我安卓手机才android19,虽然我不用安卓手机OTL.

**Comment by fython** [comment]
鉴于机器 SDK 版本低于 21 的绅士不少，可能暂时不提高到 21，但也许会考虑提高到 Jellybean MR1（17）。
