### ISSUE TITLE
对于连接网站的问题

### ISSUE THREAD

**Issue by noncharacter** [fython/NHentai-android#25]
nhentai在网页中直连都可以，而在这个app中挂载各种VPN就是才能连接，而且有时加载不出来图片，怎么回事？ 祝：高考顺利！

**Comment by noncharacter** [comment]
API中的http://nhentai换成https好像能直连。。

**Comment by eroneko** [comment]
任何图片都加载不出来呢，今天高考结束了呢

**Comment by noncharacter** [comment]
是的，app任何图片都加载不出来。我尝试把里面关于nhentai的网站改成https，可以看到封面，但点进去就闪退。。

**Comment by fython** [comment]
现在部分运营商网络可以借助 HTTPS 直连了~
