### ISSUE TITLE
Searching by tag or text gives looping result

### ISSUE THREAD

**Issue by Syborg49** [fython/NHentai-android#3]
When searching for something with tags or a name it gives looping result. Continuously showing me the same things over and over again.

**Comment by fython** [comment]
Thanks for feedback. I have found this problem, too. I will solve it in next version.

**Comment by Syborg49** [comment]
The problem still exists after 1.1.0 beta update.

**Comment by fython** [comment]
I am sorry that I haven't enough time to deal with all problems. I have realized it only happened when there was the next page for the tags or search results, but the NHentai.net wouldn't return any error info.

BTW, please keep this issue open until I really fix it.

**Comment by fython** [comment]
Fixed 45d25e91019290948be46b4ae48d55ce4b100b18
