### ISSUE TITLE
GalleryActivity的mSeekBar拖拽正常,单击有问题.

### ISSUE THREAD

**Issue by dyguests** [fython/NHentai-android#7]
作者晚上好:

拖拽时无问题,但是在单击Seekbar的时候:

        mSeekbar.setOnTouchListener((view, motionEvent) -> {
            if (motionEvent.getAction() == MotionEvent.ACTION_UP) {
                mPager.setCurrentItem(mSeekbar.getValue() - 1, false);
            }
            return view.onTouchEvent(motionEvent);
        });

1.若当前为第1页,点击seekbar的第100页.
2.此时 mSeekbar.getValue() 的取值为 1,而不是100.

分析原因是:
单击第100页后,当前seekbar还显示为第1页,在经过一个短暂的动画后,才变更为100页.

还未找到解决办法.
1.setOnPositionChangeListener会oom.(OTL)
2.因为OnTouchListener触发后才会触发OnPositionChangeListener,所以采用在OnPositionChangeListener中保存下value在OnTouchListener中再使用也不行.

**Comment by fython** [comment]
非常谢谢你的反馈和分析。
个人感觉应该可以通过修改 Seekbar 的 OnPositionChangeListener 返回是否正在 seeking，从而达到只有切换结束才更换页面（避免更换过快容易导致OOM或者其他问题），我当初这么做只是偷一下懒~

**Comment by dyguests** [comment]
或者用RxAndroid或者手写,实现间隔时间内不响应来解决oom.
因为别的漫画阅读器在拖拽的!!!过程中!!!也会跳转到新的页面,而不是只在拖拽!!!结束后!!!再跳转

**Comment by fython** [comment]
@dyguests 233333

**Comment by fython** [comment]
Fixed e5ce30339282b9e7e17cddafeb504b02037a2e5e

已用最新 Android Support Library v7 AppCompat 23.1.0 的 AppCompatSeekBar 代替

**Comment by dyguests** [comment]
Got it.
