### ISSUE TITLE
 When searching by tag, a refresh returns blank page on 1.1.0 (11)

### ISSUE THREAD

**Issue by Syborg49** [fython/NHentai-android#9]

**Comment by fython** [comment]
This problem has existed for a long time QAQ. I am going to back to school so I might have not enough time to solve it. I'm sorry for this.

In fact, you can try to do a scroll gesture on blank page and it will display normally.

**Comment by Syborg49** [comment]
No problem. School comes first. If you have time, take a look at "EHviewer" by "seven332" it has some useful features like, page jump, Right side panel and other stuff. It'd be cool if you implement those.

**Comment by fython** [comment]
Yes, I learned a lot from EhViewer project. For example, its tags view which is copied to NHBooks.

**Comment by fython** [comment]
Fixed e5ce30339282b9e7e17cddafeb504b02037a2e5e
